version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cully_postgres
    environment:
      POSTGRES_DB: cully_db
      POSTGRES_USER: cully
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cully"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: cully_mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MH_STORAGE: memory

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cully_backend
    environment:
      DATABASE_URL: postgresql://cully:password@postgres:5432/cully_db?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      PORT: 3001
      NODE_ENV: development
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASS: ""
      SMTP_FROM: noreply@cully.com
      MAX_FILE_SIZE: 10485760
      UPLOAD_PATH: ./uploads
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - upload_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cully_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    command: npm run dev -- --host

volumes:
  postgres_data:
    driver: local
  upload_data:
    driver: local

networks:
  default:
    name: cully_network