services:
  postgres:
    image: postgres:15-alpine
    container_name: cully_postgres
    environment:
      POSTGRES_DB: cully_db
      POSTGRES_USER: cully
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cully"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cully_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: cully_backend
    env_file:
      - server/.env
    ports:
      - "3001:3001"
    volumes:
      - ./server/src:/app/server/src  # Only mount the src for live reload
      - ./prisma:/app/prisma        # Mount the prisma schema
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cully_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  upload_data:
    driver: local

networks:
  default:
    name: cully_network