services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cully_postgres
    environment:
      POSTGRES_DB: cully_db
      POSTGRES_USER: cully
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cully"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: cully_mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MH_STORAGE: memory

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: cully_backend
    env_file:
      - server/.env
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app                  # Mounts the server code for live-reloading
      - ./prisma:/app/prisma            # Mounts the prisma schema so it's available at runtime
      - upload_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cully_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  upload_data:
    driver: local

networks:
  default:
    name: cully_network